### ISSUE TITLE
APIM Provisioning process

### ISSUE THREAD

**Issue by CimermanDenis** [SAP-docs/btp-integration-suite#61]
### Issue description

Hello, I think that this is not true: "If you are using a trial account, the account will be provisioned automatically. As a result, the option to access APIs will not appear under Settings in the side-navigation menu once the account is onboarded."
I noticed, that the APIM is not provisioned until I click on the APIs in the Settings in the Trial account. Only after I do this, the account is provisioned.

### Feedback Type (Optional)

incorrect statement

### Page Title on SAP Help Portal (prefilled)

Enable API Management Capability

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/integration-suite/sap-integration-suite/enabling-api-management-capability-from-integration-suite

**Comment by Karunaharan** [comment]
Hi @CimermanDenis 
Thank you for your feedback. We will check and get back to you as soon as possible.

**Comment by Kakabira** [comment]
@CimermanDenis: I need to consult with the Developer who is responsible for onboarding API Management users in Integration Suite before removing this note from the user guide. He recently asked me to include this note because trial users were experiencing issues when trying to activate and configure APIM in Integration Suite.

I will need to verify the steps for trial accounts with him before removing this note. He is currently on vacation and will be back on the 5th of May. Once he returns, I will make the necessary updates. 

Thank you for your understanding. I will keep you updated on the progress of this issue.

Thanks,
Kasturi

**Comment by Kakabira** [comment]
@CimermanDenis: After checking with the developer, I have made the necessary corrections. 
Please see:
https://help.sap.com/docs/integration-suite/sap-integration-suite/enabling-api-management-capability-from-integration-suite?version=CLOUD

**Comment by Karunaharan** [comment]
Closed as per @Kakabira's previous comment
